; https://github.com/nakst/gf/tree/master
; Compiled with extension:
;   copy the file extension.cpp in the root of the source
;   then run ./build.sh

[ui]
scale=2.3
font_size_interface=19
font_size_code=20
layout=h(65,v(75,Source,Console),v(50,t(Registers,Watch,Breakpoints,Commands,Struct,Exe,Locals),t(Stack,Files,Memory,View,Prof,Data,Thread,CmdSearch))))
